"""Markdown report exporter."""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlforensic.utils.formatting import format_row_count

if TYPE_CHECKING:
    from sqlforensic import AnalysisReport


class MarkdownReporter:
    """Export analysis results as Markdown documentation.

    Generates a comprehensive Markdown report suitable for inclusion
    in project documentation or wiki pages.
    """

    def __init__(self, report: AnalysisReport) -> None:
        self.report = report

    def export(self, output_path: str) -> None:
        """Export report to Markdown file.

        Args:
            output_path: Path to write the Markdown file.
        """
        lines = self._build()

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    def _build(self) -> list[str]:
        """Build all Markdown content."""
        lines: list[str] = []

        lines.append(f"# SQLForensic Report: {self.report.database}")
        lines.append("")
        lines.append(f"**Provider:** {self.report.provider}")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"**Health Score:** {self.report.health_score}/100")
        lines.append("")

        lines.extend(self._schema_section())
        lines.extend(self._issues_section())
        lines.extend(self._relationships_section())
        lines.extend(self._sp_section())
        lines.extend(self._index_section())
        lines.extend(self._dead_code_section())
        lines.extend(self._dependency_section())

        lines.append("")
        lines.append("---")
        lines.append("*Generated by [SQLForensic](https://github.com/mehmetcandiri/sqlforensic)*")

        return lines

    def _schema_section(self) -> list[str]:
        """Build schema overview section."""
        lines = ["## Schema Overview", ""]
        overview = self.report.schema_overview

        lines.append("| Metric | Count |")
        lines.append("|--------|------:|")
        for key, value in overview.items():
            label = key.replace("_", " ").title()
            lines.append(
                f"| {label} | {format_row_count(value) if isinstance(value, int) else value} |"
            )
        lines.append("")

        # Tables list
        if self.report.tables:
            lines.append("### Tables")
            lines.append("")
            lines.append("| Schema | Table | Columns | Rows | PK |")
            lines.append("|--------|-------|--------:|-----:|:--:|")
            for t in self.report.tables:
                pk = "Yes" if t.get("has_primary_key") else "**No**"
                lines.append(
                    f"| {t.get('TABLE_SCHEMA', '')} "
                    f"| {t.get('TABLE_NAME', '')} "
                    f"| {t.get('column_count', 0)} "
                    f"| {format_row_count(t.get('row_count', 0))} "
                    f"| {pk} |"
                )
            lines.append("")

        return lines

    def _issues_section(self) -> list[str]:
        """Build issues section."""
        if not self.report.issues:
            return []

        lines = ["## Issues", ""]
        lines.append("| Issue | Severity | Count |")
        lines.append("|-------|----------|------:|")
        for issue in self.report.issues:
            lines.append(
                f"| {issue['description']} "
                f"| {issue.get('severity', 'INFO')} "
                f"| {issue.get('count', 0)} |"
            )
        lines.append("")
        return lines

    def _relationships_section(self) -> list[str]:
        """Build relationships section."""
        lines = ["## Relationships", ""]

        if self.report.relationships:
            lines.append(f"### Foreign Keys ({len(self.report.relationships)})")
            lines.append("")
            lines.append("| Parent Table | Column | Referenced Table | Referenced Column |")
            lines.append("|-------------|--------|-----------------|-------------------|")
            for rel in self.report.relationships:
                lines.append(
                    f"| {rel.get('parent_table', '')} "
                    f"| {rel.get('parent_column', '')} "
                    f"| {rel.get('referenced_table', '')} "
                    f"| {rel.get('referenced_column', '')} |"
                )
            lines.append("")

        if self.report.implicit_relationships:
            lines.append(f"### Implicit Relationships ({len(self.report.implicit_relationships)})")
            lines.append("")
            lines.append("| Parent | Column | Referenced | Confidence | Source |")
            lines.append("|--------|--------|-----------|:----------:|--------|")
            for rel in self.report.implicit_relationships:
                lines.append(
                    f"| {rel.get('parent_table', '')} "
                    f"| {rel.get('parent_column', '')} "
                    f"| {rel.get('referenced_table', '')} "
                    f"| {rel.get('confidence', 0)}% "
                    f"| {rel.get('source', '')} |"
                )
            lines.append("")

        return lines

    def _sp_section(self) -> list[str]:
        """Build stored procedure analysis section."""
        if not self.report.sp_analysis:
            return []

        lines = ["## Stored Procedure Analysis", ""]
        lines.append("| Name | Lines | Joins | Tables | Complexity | Score |")
        lines.append("|------|------:|------:|-------:|------------|------:|")
        for sp in self.report.sp_analysis[:30]:
            lines.append(
                f"| {sp.get('name', '')} "
                f"| {sp.get('line_count', 0)} "
                f"| {sp.get('join_count', 0)} "
                f"| {len(sp.get('referenced_tables', []))} "
                f"| {sp.get('complexity_category', 'Simple')} "
                f"| {sp.get('complexity_score', 0)} |"
            )
        lines.append("")
        return lines

    def _index_section(self) -> list[str]:
        """Build index analysis section."""
        lines = ["## Index Analysis", ""]

        if self.report.missing_indexes:
            lines.append(f"### Missing Indexes ({len(self.report.missing_indexes)})")
            lines.append("")
            for idx in self.report.missing_indexes[:10]:
                lines.append(
                    f"- **{idx.get('table_name', '')}**: {idx.get('equality_columns', '')}"
                )
                lines.append("  ```sql")
                lines.append(f"  {idx.get('create_sql', '')}")
                lines.append("  ```")
            lines.append("")

        if self.report.unused_indexes:
            lines.append(f"### Unused Indexes ({len(self.report.unused_indexes)})")
            lines.append("")
            for idx in self.report.unused_indexes[:10]:
                lines.append(f"- `{idx.get('index_name', '')}` on `{idx.get('table_name', '')}`")
            lines.append("")

        return lines

    def _dead_code_section(self) -> list[str]:
        """Build dead code section."""
        lines = ["## Dead Code", ""]

        if self.report.dead_tables:
            lines.append(f"### Unreferenced Tables ({len(self.report.dead_tables)})")
            lines.append("")
            for t in self.report.dead_tables:
                lines.append(
                    f"- `{t.get('TABLE_SCHEMA', '')}.{t.get('TABLE_NAME', '')}`"
                    f" ({format_row_count(t.get('row_count', 0))} rows)"
                )
            lines.append("")

        if self.report.dead_procedures:
            lines.append(f"### Unused Procedures ({len(self.report.dead_procedures)})")
            lines.append("")
            for sp in self.report.dead_procedures:
                lines.append(f"- `{sp.get('ROUTINE_SCHEMA', '')}.{sp.get('ROUTINE_NAME', '')}`")
            lines.append("")

        return lines

    def _dependency_section(self) -> list[str]:
        """Build dependency section."""
        lines = ["## Dependencies", ""]

        if self.report.circular_dependencies:
            lines.append(f"### Circular Dependencies ({len(self.report.circular_dependencies)})")
            lines.append("")
            for cycle in self.report.circular_dependencies:
                if cycle:
                    lines.append(f"- {' -> '.join(cycle)} -> {cycle[0]}")
            lines.append("")

        deps = self.report.dependencies
        if isinstance(deps, dict) and deps.get("hotspots"):
            lines.append("### Dependency Hotspots")
            lines.append("")
            lines.append("| Table | Dependent SPs | Risk |")
            lines.append("|-------|-------------:|------|")
            for hs in deps["hotspots"][:10]:
                lines.append(
                    f"| {hs['table']} "
                    f"| {hs['dependent_sp_count']} "
                    f"| {hs.get('risk_level', 'LOW')} |"
                )
            lines.append("")

        return lines
